# .github/workflows/check.yml

name: Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Type Check
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            nettle-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            clang \
            llvm \
            libssl-dev \
            libpq-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Type Check
        run: cargo check

      - name: Run Tests
        run: cargo test
