name: Release Build and Upload

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # MSYS2 環境構築
      - name: Setup MSYS2 on Windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: |
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-nettle

      # 既存 Rustup を削除して新規インストールに強制
      - name: Clean existing Rustup
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          rm -rf /home/runneradmin/.cargo
          rm -rf /home/runneradmin/.rustup

      # MSYS2 内で Rust を新規インストール
      - name: Install Rust in MSYS2
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          source "$HOME/.cargo/env"

      # 4. macOS x86_64 用依存インストール
      - name: Install system dependencies on macOS (Intel)
        if: runner.os == 'macOS' && matrix.target == 'x86_64-apple-darwin'
        run: |
          brew update
          brew reinstall nettle pkgconf

      # クロス用ラッパーの生成（Linux/macOS）
      - name: Generate pkg-config wrapper
        if: runner.os != 'Windows'
        run: |
          cat << 'EOF' > ./target-pkg-config
          #!/usr/bin/env sh
          SYSROOT="/usr/${{ matrix.target }}"
          export PKG_CONFIG_DIR=
          export PKG_CONFIG_LIBDIR="${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig"
          export PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
          export PKG_CONFIG_ALLOW_CROSS=1
          exec pkg-config "$@"
          EOF
          chmod +x ./target-pkg-config

      # 5. Linux 用依存インストール
      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            nettle-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libjavascriptcoregtk-4.1-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev \
            clang \
            llvm \
            libssl-dev \
            libpq-dev

      # 6. Rust ツールチェーンセットアップ (非 Windows)
      - name: Setup Rust toolchain for non-Windows
        if: runner.os != 'Windows'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          target: ${{ matrix.target }}

      # 7. Windows: 共通ライブラリビルド（MSYS2 Bash）
      - name: Build common library (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          export PKG_CONFIG_ALLOW_SYSTEM_LIBS=1
          export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
          cargo build --release --target ${{ matrix.target }} -p common

      # 8. Linux/macOS: 共通ライブラリビルド
      - name: Build common library (Linux/macOS)
        if: runner.os != 'Windows'
        env:
          PKG_CONFIG: ${{ github.workspace }}/target-pkg-config
        run: cargo build --release --target ${{ matrix.target }} -p common

      # 9. Windows: Tauri アプリビルド（MSYS2 Bash）
      - name: Build Tauri App (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd client-tauri
          export PKG_CONFIG_ALLOW_SYSTEM_LIBS=1
          export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
          cargo tauri build --release --target ${{ matrix.target }}

      # 10. Linux/macOS: Tauri アプリビルド
      - name: Build Tauri App (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd client-tauri
          cargo tauri build --release --target ${{ matrix.target }}

      # 11. バンドルを ZIP 化してリリースへアップロード
      - name: Archive bundles
        run: |
          zip -r release-${{ matrix.target }}.zip \
            client-tauri/target/${{ matrix.target }}/release/bundle \
            target/${{ matrix.target }}/release/libcommon.rlib

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-${{ matrix.target }}.zip
          asset_name: release-${{ matrix.target }}.zip
          asset_content_type: application/zip
