name: Release Build and Upload

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config nettle-dev libssl-dev libpq-dev clang llvm

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          target: ${{ matrix.target }}

      - name: Generate pkg-config wrapper
        run: |
          cat << 'EOF' > ./target-pkg-config
          #!/usr/bin/env sh
          SYSROOT="/usr/${{ matrix.target }}"
          export PKG_CONFIG_DIR=
          export PKG_CONFIG_LIBDIR="${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig"
          export PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
          export PKG_CONFIG_ALLOW_CROSS=1
          exec pkg-config "$@"
          EOF
          chmod +x ./target-pkg-config

      - name: Build common library
        env:
          PKG_CONFIG: ${{ github.workspace }}/target-pkg-config
        run: cargo build --release --target ${{ matrix.target }} -p common

      - name: Build Tauri App
        working-directory: client-tauri
        env:
          PKG_CONFIG: ${{ github.workspace }}/target-pkg-config
        run: pnpm tauri build --release

      - name: Archive bundles
        run: |
          zip -r release-${{ matrix.target }}.zip \
            client-tauri/target/${{ matrix.target }}/release/bundle \
            target/${{ matrix.target }}/release/libcommon.rlib

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-${{ matrix.target }}.zip
          asset_name: release-${{ matrix.target }}.zip
          asset_content_type: application/zip
