# GitHub Actions: Release Build and Upload

name: Release Build and Upload

on:
  release:
    types: [created] # GitHub Release 作成時にトリガー

jobs:
  publish:
    name: Build and Release (linux)
    permissions:
      contents: write # Release への書き込み権限
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            nettle-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libjavascriptcoregtk-4.1-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev \
            clang \
            llvm \
            libssl-dev \
            libpq-dev

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Build common library
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu -p common

      - name: Build & Release Tauri App
        id: tauri
        uses: tauri-apps/tauri-action@v0.5.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: client-tauri
          args: --target x86_64-unknown-linux-gnu --release

      - name: Upload common artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tauri-action の出力変数名は releaseUploadUrl
          upload_url: ${{ steps.tauri.outputs.releaseUploadUrl }}
          # Linux x86_64 ターゲットに合わせてハードコード
          asset_path: target/x86_64-unknown-linux-gnu/release/libcommon.rlib
          asset_name: libcommon-x86_64-unknown-linux-gnu.rlib
          asset_content_type: application/octet-stream
