name: Release Build and Upload

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            nettle-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libjavascriptcoregtk-4.1-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev \
            clang \
            llvm \
            libssl-dev \
            libpq-dev

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          target: ${{ matrix.target }}

      - name: Build common library
        run: cargo build --release  -p common

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install client dependencies
        working-directory: client-tauri
        run: npm install

      - name: Build Tauri App
        working-directory: client-tauri
        run: npm run tauri build --release

      - name: Archive bundles
        run: |
          zip -r release-${{ matrix.target }}.zip \
            client-tauri/target/${{ matrix.target }}/release/bundle \
            target/${{ matrix.target }}/release/libcommon.rlib

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-${{ matrix.target }}.zip
          asset_name: release-${{ matrix.target }}.zip
          asset_content_type: application/zip
